// pages/index.tsx

import Head from "next/head";
import Image from "next/image";
import { Nav } from "../components/Nav";
import { Product } from "../components/Product";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Frontend Mentor | E-commerce product page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen max-w-[1024px] m-auto">
        <Nav />
        <Product
          company="Sneaker Company"
          name="Fall Limited Edition Sneakers"
          description="These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they’ll withstand everything the weather can offer."
          originalPrice={250}
          discount={50}
        />
      </main>

      <footer className="flex flex-row justify-center">
        <p>
          Challenge by{" "}
          <a
            href="https://www.frontendmentor.io/challenges/ecommerce-product-page-UPsZ9MJp6"
            target="_blank"
            rel="noreferrer"
          >
            Frontend Mentor
          </a>
          . Coded by{" "}
          <a
            href="https://github.com/philliplam8/ecommerce-product-page-app-challenge"
            target="_blank"
            rel="noreferrer"
          >
            Phillip Lam
          </a>
          .
        </p>
      </footer>
    </div>
  );
}
