// pages/index.tsx

import Head from "next/head";
import { Nav } from "../components/Nav";
import { Product } from "../components/Product";

export default function Home() {
  // Demo Product Details
  const originalPrice: number = 250;
  const discount: number = 50;
  const discountedPrice: number = (originalPrice * discount) / 100;

  return (
    <div>
      <Head>
        <title>Frontend Mentor | E-commerce product page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-[1024px] m-auto">
        <Nav />
        <Product
          company="Sneaker Company"
          name="Fall Limited Edition Sneakers"
          description="These low-profile sneakers are your perfect casual wear companion. Featuring a durable rubber outer sole, they’ll withstand everything the weather can offer."
          originalPrice={originalPrice}
          discount={discount}
          discountedPrice={discountedPrice}
        />
      </main>

      <footer className="flex flex-row justify-center py-5 text-xs">
        <p>
          Challenge by{" "}
          <a
            href="https://www.frontendmentor.io/challenges/ecommerce-product-page-UPsZ9MJp6"
            target="_blank"
            rel="noreferrer"
            className="font-bold"
          >
            Frontend Mentor
          </a>
          . Coded by{" "}
          <a
            href="https://github.com/philliplam8/ecommerce-product-page-app-challenge"
            target="_blank"
            rel="noreferrer"
            className="font-bold"
          >
            Phillip Lam
          </a>
          .
        </p>
      </footer>
    </div>
  );
}
